robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_rear_wheel_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}

  left_upper_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_upper_wheel_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}

  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}

  right_upper_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_upper_wheel_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}

  arm1_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: arm1_joint
    pid: {p: 30.0, i: 0.0, d: 0.0}

  arm2_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: arm2_joint
    pid: {p: 30.0, i: 0.0, d: 0.0}

  right_gripper_controller:
    type: effort_controllers/JointVelocityController
    joint: right_gripper_joint
    pid: {p: 30.0, i: 0.0, d: 0.0}

  left_gripper_controller:
    type: effort_controllers/JointVelocityController
    joint: left_gripper_joint
    pid: {p: 30.0, i: 0.0, d: 0.0}